name: test

on:
  workflow_call:
  workflow_dispatch:

env:
  CACHE_DIR: dist
  CACHE_TEST_DIR: cache-test
  MAIN_PACKAGE_PATH: .

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node:
          - '18.x'
          - '20.x'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Calculate build-cache key
        # Because the exact same hashFiles invocation produces different
        # results down the file
        id: build-cache-key
        run: |
          if command -v shasum; then sum() { shasum -a 256 "$@"; } ; else sum() { sha256sum "$@"; }; fi
          fragment=$(< package.json command grep 'version"\|"name"\|"files"\|"main"\|"build' | sum | command head -c8)
          runner_os=${{ runner.os }}

          # Make Windows use compiled outputs from other OS (anything but Windows)
          if [[ ${{ runner.os }} == "windows-"* ]]; then
            runner_os=macos-latest
          fi

          echo "key=build-$runner_os-${{ matrix.node }}-${{ hashFiles('**/src/**', '**/.swcrc', '**/.npmrc', '**/tsconfig*.json', '**/pnpm-lock.yaml', '.github/workflows/build.yml') }}-${fragment}" | tee -a $GITHUB_OUTPUT
        shell: bash

      - name: Calculate a fragment of cache key
        id: cache-key
        run: |
          if command -v shasum; then sum() { shasum -a 256 "$@"; } ; else sum() { sha256sum "$@"; }; fi
          echo "fragment=$(< package.json command grep '"test"' | sum | command head -c8)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore test cache
        id: test_cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_TEST_DIR }}
          key: tests-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/src/**', '**/.swcrc', '**/.npmrc', '**/tsconfig*.json', '**/pnpm-lock.yaml', '.github/workflows/build.yml', '.github/workflows/test.yml') }}-${{ steps.cache-key.outputs.fragment }}

      - uses: actions/setup-node@v3
        if: steps.test_cache.outputs.cache-hit != 'true'
        id: setup-node
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2
        if: steps.test_cache.outputs.cache-hit != 'true'
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      # See: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Get pnpm store directory
        if: steps.test_cache.outputs.cache-hit != 'true'
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        if: steps.test_cache.outputs.cache-hit != 'true'
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/.npmrc', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: steps.test_cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Restore build cache
        if: steps.test_cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ steps.build-cache-key.outputs.key }}

      - if: steps.test_cache.outputs.cache-hit != 'true'
        run: |
          pnpm run test:unit
          mkdir -p ${{ env.CACHE_TEST_DIR }}
          touch ${{ env.CACHE_TEST_DIR }}/pass
